In [0]:
import io
import pandas as pd
X = pd.read_csv('/content/X.csv')
y = pd.read_csv('/content/y.csv')
# Dataset is now stored in a Pandas Dataframe

In [0]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

import numpy as np

In [40]:
X

lat       long  DOMICILIO_RENDA_V001  ...  Cod_RM_6  Cod_RM_7  Cod_RM_8
0     -22.802093 -47.289667                   0.0  ...       0.0       0.0       0.0
1     -21.753831 -48.816028                   0.0  ...       0.0       0.0       0.0
2     -23.117549 -46.556707                   0.0  ...       0.0       0.0       0.0
3     -23.648112 -46.753781                   0.0  ...       0.0       0.0       0.0
4     -22.981569 -47.501046                   0.0  ...       0.0       0.0       0.0
...          ...        ...                   ...  ...       ...       ...       ...
33083  -9.586743 -35.759250                   0.0  ...       0.0       0.0       0.0
33084  -9.545163 -35.733649                   0.0  ...       0.0       0.0       0.0
33085  -9.637312 -35.700944                   0.0  ...       0.0       0.0       0.0
33086  -9.674570 -35.756639                   0.0  ...       0.0       0.0       0.0
33087  -9.543106 -35.757858                   0.0  ...       0.0       0.0       0.0

[33088 rows x 212 columns]

In [0]:
#Create train and test sets
X = StandardScaler().fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
X

array([[-0.10598204, -0.1389995 , -0.10599054, ...,  0.        ,
        -0.11297616, -0.07228708],
       [ 0.13230916, -0.57189068, -0.10599054, ...,  0.        ,
        -0.11297616, -0.07228708],
       [-0.17769159,  0.06887531, -0.10599054, ...,  0.        ,
        -0.11297616, -0.07228708],
       ...,
       [ 2.88663979,  3.14767734, -0.10599054, ...,  0.        ,
        -0.11297616, -0.07228708],
       [ 2.87817034,  3.13188149, -0.10599054, ...,  0.        ,
        -0.11297616, -0.07228708],
       [ 2.90805475,  3.13153588, -0.10599054, ...,  0.        ,
        -0.11297616, -0.07228708]])

In [0]:
# baseline model
def create_baseline():
    # create model
    model = Sequential()
    model.add(Dense(212, input_dim=212, activation='relu'))
    model.add(Dense(80, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer= 'adam', metrics=['accuracy'])
    return model

In [44]:
# evaluate model with standardized dataset
model = KerasClassifier(build_fn=create_baseline)


parameters = {'batch_size': [256],
          'epochs': [10]}


grid_search = GridSearchCV(estimator = model,
                       param_grid = parameters,
                       scoring = 'accuracy',
                       cv = 10)

grid_search = grid_search.fit(X_train, y_train, verbose = 2)

#Print the tuned parameter and score
print("Tuned neural network Parameters: {}".format(grid_search.best_params_))
print("Best score is {}".format(grid_search.best_score_))

Epoch 1/10
 - 1s - loss: 0.5591 - accuracy: 0.7162
Epoch 2/10
 - 0s - loss: 0.5344 - accuracy: 0.7324
Epoch 3/10
 - 0s - loss: 0.5279 - accuracy: 0.7397
Epoch 4/10
 - 0s - loss: 0.5257 - accuracy: 0.7386
Epoch 5/10
 - 0s - loss: 0.5210 - accuracy: 0.7419
Epoch 6/10
 - 0s - loss: 0.5170 - accuracy: 0.7455
Epoch 7/10
 - 0s - loss: 0.5144 - accuracy: 0.7446
Epoch 8/10
 - 0s - loss: 0.5105 - accuracy: 0.7469
Epoch 9/10
 - 0s - loss: 0.5132 - accuracy: 0.7460
Epoch 10/10
 - 0s - loss: 0.5092 - accuracy: 0.7515
Epoch 1/10
 - 0s - loss: 0.5581 - accuracy: 0.7160
Epoch 2/10
 - 0s - loss: 0.5333 - accuracy: 0.7324
Epoch 3/10
 - 0s - loss: 0.5293 - accuracy: 0.7327
Epoch 4/10
 - 0s - loss: 0.5249 - accuracy: 0.7394
Epoch 5/10
 - 0s - loss: 0.5224 - accuracy: 0.7374
Epoch 6/10
 - 0s - loss: 0.5188 - accuracy: 0.7399
Epoch 7/10
 - 0s - loss: 0.5140 - accuracy: 0.7449
Epoch 8/10
 - 0s - loss: 0.5120 - accuracy: 0.7475
Epoch 9/10
 - 0s - loss: 0.5108 - accuracy: 0.7457
Epoch 10/10
 - 0s - loss: 0.50

In [45]:
y_pred = grid_search.predict(X_test)



print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


0.7361740707162284
[[3145  694]
 [1052 1727]]
              precision    recall  f1-score   support

           0       0.75      0.82      0.78      3839
           1       0.71      0.62      0.66      2779

    accuracy                           0.74      6618
   macro avg       0.73      0.72      0.72      6618
weighted avg       0.73      0.74      0.73      6618



In [46]:
# evaluate model with standardized dataset
model = KerasClassifier(build_fn=create_baseline)


parameters = {'batch_size': [1000, 1200, 1300, 1500],
          'epochs': [8, 9, 10, 11, 15]}


grid_search = GridSearchCV(estimator = model,
                       param_grid = parameters,
                       scoring = 'accuracy',
                       cv = 5)

grid_search = grid_search.fit(X_train, y_train, verbose = 0)

#Print the tuned parameter and score
print("Tuned neural network Parameters: {}".format(grid_search.best_params_))
print("Best score is {}".format(grid_search.best_score_))

Tuned neural network Parameters: {'batch_size': 1000, 'epochs': 10}
Best score is 0.7349452210049112


In [47]:
y_pred = grid_search.predict(X_test)



print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7384406165004533
[[3086  753]
 [ 978 1801]]
              precision    recall  f1-score   support

           0       0.76      0.80      0.78      3839
           1       0.71      0.65      0.68      2779

    accuracy                           0.74      6618
   macro avg       0.73      0.73      0.73      6618
weighted avg       0.74      0.74      0.74      6618



In [58]:
y_pred = grid_search.predict_proba(X_test)[:,1] > 0.45
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7361740707162284
[[2922  917]
 [ 829 1950]]
              precision    recall  f1-score   support

           0       0.78      0.76      0.77      3839
           1       0.68      0.70      0.69      2779

    accuracy                           0.74      6618
   macro avg       0.73      0.73      0.73      6618
weighted avg       0.74      0.74      0.74      6618



In [50]:
# model to serialize
model = KerasClassifier(build_fn=create_baseline, batch_size= 1000, epochs=10)

model.fit(X_train, y_train, verbose = 2)



Epoch 1/10
 - 0s - loss: 0.5645 - accuracy: 0.7120
Epoch 2/10
 - 0s - loss: 0.5333 - accuracy: 0.7318
Epoch 3/10
 - 0s - loss: 0.5253 - accuracy: 0.7365
Epoch 4/10
 - 0s - loss: 0.5219 - accuracy: 0.7376
Epoch 5/10
 - 0s - loss: 0.5170 - accuracy: 0.7408
Epoch 6/10
 - 0s - loss: 0.5137 - accuracy: 0.7440
Epoch 7/10
 - 0s - loss: 0.5097 - accuracy: 0.7453
Epoch 8/10
 - 0s - loss: 0.5088 - accuracy: 0.7474
Epoch 9/10
 - 0s - loss: 0.5059 - accuracy: 0.7506
Epoch 10/10
 - 0s - loss: 0.5033 - accuracy: 0.7502


In [51]:
from google.colab import files

# save model and architecture to single file
model.model.save("model.h5")
print("Saved model to disk")

files.download("model.h5")

Saved model to disk
